-- 코드를 입력하세요
-- 2022년 1월 도서 판매 데이터 만들기
WITH SALE_DATA AS 
(SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK_ID),

-- 저자ID, 저자 이름, 카테고리, 토탈 금액
 BASE AS (
    SELECT A.AUTHOR_ID, AUTHOR_NAME, B.BOOK_ID, B.CATEGORY, B.PRICE FROM AUTHOR A
    LEFT JOIN BOOK B USING(AUTHOR_ID)
    WHERE BOOK_ID IS NOT NULL
),
CTE AS(
SELECT *, (PRICE*SALES) AS 'TOTAL_SALES' FROM SALE_DATA AS SD
LEFT JOIN BASE AS B USING(BOOK_ID))

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) FROM CTE
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC