-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, 
round(count(DISTINCT O.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O JOIN USER_INFO I on o.user_id = i.user_id WHERE YEAR(SALES_DATE) = 2022 
AND YEAR(i.joined) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE) ORDER BY YEAR ASC, MONTH ASC;