-- 코드를 작성해주세요
WITH CNT AS(
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
    )
SELECT DISTINCT ID  , IFNULL(CHILD_COUNT,0) AS CHILD_COUNT FROM ECOLI_DATA
LEFT JOIN CNT ON ID=CNT.PARENT_ID
ORDER BY 1

