WITH HISTORY AS(
-- 11월 이하에서 ~~ 11월 1일 이상 까지 빌리는 경우
-- 시작 날짜가 11월 1일 ~ 11월 30일 까지 빌리는 경우
-- 끝 날자가 11월 1일~ 11월 30일 까지 인 경우
SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE (DATE_FORMAT(START_DATE,'%y-%m-%d') BETWEEN '22-11-01' AND '22-11-30') 
        OR (DATE_FORMAT(END_DATE,'%y-%m-%d') BETWEEN '22-11-01' AND '22-11-30')
        OR ((DATE_FORMAT(START_DATE,'%y-%m-%d')<'22-11-01') AND (DATE_FORMAT(END_DATE,'%y-%m-%d')>'22-11-30'))
        ORDER BY CAR_ID
)
, CAN_RENT AS (
    SELECT * FROM CAR_RENTAL_COMPANY_CAR AS CAR 
    WHERE CAR_ID NOT IN(SELECT * FROM HISTORY) AND CAR_TYPE IN('세단','SUV')
)

SELECT CAR_ID, CAR_TYPE, FEE FROM (SELECT *, ROUND((DAILY_FEE * 30 * ((100-DISCOUNT_RATE)*0.01)),0) AS FEE FROM CAN_RENT INNER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') DP
USING(CAR_TYPE)) ANS
WHERE FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC