-- 코드를 작성해주세요
WITH CTE AS (SELECT ID, TRUNCATE(PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY ),2) AS SIZE_DATA FROM ECOLI_DATA)

SELECT ID, 
    (CASE 
    WHEN 1-SIZE_DATA <= 0.25 THEN 'CRITICAL'
    WHEN 1-SIZE_DATA <= 0.5 THEN 'HIGH'
    WHEN 1-SIZE_DATA <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END) AS COLONY_NAME
    FROM CTE
    ORDER BY ID ASC