-- 코드를 입력하세요
-- 보호소에서
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS AS A JOIN ANIMAL_INS AS B ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE LOWER(SEX_UPON_INTAKE) LIKE '%intact%'
AND LOWER(SEX_UPON_OUTCOME) != LOWER(SEX_UPON_INTAKE)
order by animal_id