WITH CTE AS(
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE ('%Spayed%') OR SEX_UPON_INTAKE LIKE ('%Neutered%'))

SELECT AI.ANIMAL_ID, NAME, 
    CASE 
        WHEN CTE.ANIMAL_ID IS NULL
        THEN 'X'
        ELSE 'O'
    END AS '중성화'
    FROM ANIMAL_INS AI
LEFT JOIN CTE ON AI.ANIMAL_ID = CTE.ANIMAL_ID
ORDER BY AI.ANIMAL_ID