-- 코드를 작성해주세요
-- 역 사이 거리 -> D_BWTWEEN_DIST
-- 노선별 누계 거리 -> D_CUMULATIVE
-- 역 사이 거리의 총 합을 뜻한다. (총 누계 거리)
SELECT ROUTE, 
concat(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, 
concat(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC