-- 코드를 입력하세요
# SELECT  F.FLAVOR, (F.TOTAL_ORDER + J.TOTAL_ORDER)  FROM FIRST_HALF  AS F
# LEFT JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
# GROUP BY FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC 
# LIMIT 3

SELECT FLAVOR
FROM (SELECT * FROM FIRST_HALF
UNION ALL
SELECT * FROM JULY) AS A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
