-- 코드를 입력하세요
SELECT AP.APNT_NO,PT.PT_NAME,PT.PT_NO, AP.MCDP_CD ,DOC.DR_NAME, APNT_YMD FROM APPOINTMENT AP
LEFT JOIN DOCTOR DOC ON MDDR_ID = DOC.DR_ID
LEFT JOIN PATIENT PT USING (PT_NO)
WHERE APNT_CNCL_YN = 'N' AND DATE_FORMAT(APNT_YMD,"%y-%m-%d") = "22-04-13"
ORDER BY APNT_YMD ASC