WITH TOTAL_PRICE AS(
    SELECT WRITER_ID, SUM(PRICE) AS PRICE_SUM
    FROM USED_GOODS_BOARD
    WHERE STATUS LIKE('DONE')
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, PRICE_SUM FROM USED_GOODS_USER AS U
JOIN TOTAL_PRICE AS TP 
ON U.USER_ID = TP.WRITER_ID
ORDER BY PRICE_SUM ASC

# SELECT WRITER_ID, PRICE, SUM(PRICE) FROM USED_GOODS_BOARD
# WHERE WRITER_ID = 'dhfkzmf09'