-- 코드를 입력하세요
# SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS

SELECT DATE_FORMAT(DATETIME,'%H') as hour, count(*)
FROM ANIMAL_OUTS 
where  DATE_FORMAT(DATETIME,'%H') >= 9  AND DATE_FORMAT(DATETIME,'%H') < 20
GROUP BY hour
order by hour asc
