-- 코드를 작성해주세요
WITH TOP AS(
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
    GROUP BY FISH_TYPE)
    
SELECT FI.ID, FISH_NAME, FI.LENGTH 
FROM FISH_INFO FI
JOIN FISH_NAME_INFO
USING (FISH_TYPE)
WHERE (FI.FISH_TYPE, FI.LENGTH) IN 
(SELECT * FROM TOP)
ORDER BY FI.ID
