-- 코드를 작성해주세요
SELECT fi.id, fish_name, length FROM FISH_INFO FI
INNER JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE fish_type IN
(
    SELECT FISH_TYPE FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY FI.ID