-- 코드를 작성해주세요
WITH CTE AS (SELECT SUM(SCORE)AS SCORE, EMP_NO, YEAR FROM HR_GRADE HG
WHERE YEAR = 2022
GROUP BY EMP_NO, YEAR
ORDER BY SCORE DESC LIMIT 1)

SELECT CTE.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL FROM HR_EMPLOYEES AS HE
LEFT JOIN CTE USING(EMP_NO)
WHERE SCORE IS NOT NULL