-- 코드를 입력하세요
# SELECT TITLE, BO.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
# DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD BO, USED_GOODS_REPLY UGR
# WHERE BO.BOARD_ID = UGR.BOARD_ID 
# AND DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m') = '2022-10'
# order by UGR.CREATED_DATE asc, title asc

SELECT TITLE, BO.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD BO 
RIGHT JOIN USED_GOODS_REPLY UGR ON BO.BOARD_ID = UGR.BOARD_ID 
WHERE DATE_FORMAT(BO.CREATED_DATE, '%Y-%m') = '2022-10'
order by UGR.CREATED_DATE asc, title asc