-- 코드를 입력하세요
# SELECT TITLE, BO.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
# DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD BO, USED_GOODS_REPLY UGR
# WHERE BO.BOARD_ID = UGR.BOARD_ID 
# AND DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m') = '2022-10'
# order by UGR.CREATED_DATE asc, title asc

# SELECT TITLE, BO.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS,
# DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD BO 
# LEFT JOIN USED_GOODS_REPLY UGR ON BO.BOARD_ID = UGR.BOARD_ID 
# WHERE DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m') = '2022-10' and reply_id is not null
# order by UGR.CREATED_DATE asc, title asc

SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS,  
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d')AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE ASC, TITLE ASC