-- 코드를 입력하세요
WITH CTE AS(
SELECT BOARD_ID AS ID, VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)

SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH FROM USED_GOODS_FILE
WHERE USED_GOODS_FILE.BOARD_ID = (SELECT ID FROM CTE)
ORDER BY 1 DESC