-- 코드를 작성해주세요
-- 
WITH PRE AS(
SELECT id, fish_type, IFNULL(LENGTH,10) AS LENGTH FROM FISH_INFO)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE AS FISH_TYPE FROM PRE
GROUP BY FISH_TYPE
HAVING AVG(LENGTH)> (33)
ORDER BY FISH_TYPE ASC
# SELECT ID,FISH_TYPE,LENGTH,TIME FROM PRE;